version: '3'
services:
  database:
    image: postgres # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=stage
      - POSTGRES_HOST_AUTH_METHOD=trust
    user: 1000:1000
    volumes:
      - ./data:/var/lib/postgresql/data # persist data even if container shuts down
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    environment: 
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=database
      - POSTGRES_DB=stage
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - "8000:8000"
    depends_on: 
      - database

  # web:
  #   image: nginx
  #   volumes:
  #     - ./nginx/project.conf:/etc/nginx/conf.d/default.conf

